- id: doi:10.1145/3731599.3767520
- id: doi:10.1145/3731599.3767393
- id: url:https://sc25.supercomputing.org/proceedings/posters/poster_pages/post197.html
  title: Optimizing the GPU All-Reduce Using Multiple Processes per GPU
  author: Michael Adams and Amanda Bienz
  publisher: Supercomputing 2025
  date: November, 2025
  type: papar
  description: SC'25 research poster by Michael Adams
