blank_issues_enabled: true
contact_links:
  - name: Website content question
    url: https://github.com/COMPASS-PSAAP/compass-psaap.github.io/issues
    about: Ask a general question about site content, member profiles, or project listings.
